system:
  num_cdus: 6
  racks_per_cdu: 6
  nodes_per_rack: 80
  rectifiers_per_rack: 6
  chassis_per_rack: 1
  nodes_per_blade: 1
  switches_per_chassis: 5
  nics_per_node: 2
  rectifiers_per_chassis: 5
  nodes_per_rectifier: 4
  missing_racks: []
  down_nodes: []
  cpus_per_node: 1
  gpus_per_node: 4
  cpu_peak_flops: 396800000000.0
  gpu_peak_flops: 7800000000000.0
  cpu_fp_ratio: 0.69
  gpu_fp_ratio: 0.69

power:
  power_gpu_idle: 75
  power_gpu_max: 300
  power_cpu_idle: 100
  power_cpu_max: 800
  power_mem: 74.26
  power_nic: 21
  power_nvme: 45
  power_switch: 250
  power_cdu: 0
  power_update_freq: 20
  rectifier_peak_threshold: 13670
  sivoc_loss_constant: 0
  sivoc_efficiency: 1
  rectifier_loss_constant: 0
  rectifier_efficiency: 1
  power_cost: 0.094

scheduler:
  seed: 42
  job_arrival_time: 20
  mtbf: 11
  trace_quanta: 20
  min_wall_time: 3600
  max_wall_time: 43200
  ui_update_freq: 3600
  max_nodes_per_job: 3000
  job_end_probs:
    COMPLETED: 0.63
    FAILED: 0.13
    CANCELLED: 0.12
    TIMEOUT: 0.11
    NODE_FAIL: 0.01